"""
"Mysql : \n",
    "    \n",
    "    1. Create a  table attribute dataset and dress dataset\n",
    "    2. Do a bulk load for these two table for respective dataset \n",
    "    3. read these dataset in pandas as a dataframe \n",
    "    4. Convert attribute dataset in json format \n",
    "    5. Store this dataset into mongodb\n",
    "    6. in sql task try to perform left join operation with attrubute dataset and dress dataset on column Dress_ID\n",
    "    7. Write a sql query to find out how many unique dress that we have based on dress id \n",
    "    8. Try to find out how mnay dress is having recommendation 0\n",
    "    9. Try to find out total dress sell for individual dress id \n",
    "    10. Try to find out a third highest most selling dress id \n",
    "    \n",
    "    \n",
    "    sudhanshu@ineuron.ai\n",
"""